name: ranjith devops

on: push

jobs:
  orange:
    runs-on: ubuntu-latest
    steps:
      - name: easy
        run: echo "hello world"
      
  mango:
    runs-on: ubuntu-latest
    steps:
      - name: moderate
        run: echo "moderate is running"
