name: welcome

on: [push]

jobs:
  first_job:
    runs-on: ubuntu-22.04
    
    steps:
     - name: cool
       run: |
           echo "hello world" > file.txt
           cat file.txt
     - name: welcome
       run: |
          ls
          pwd
          whoami
