name: maheshbabu
on: [push]
jobs:
  livelong:
    runs-on: ubuntu-22.04

    steps:
      - name: loki
        run: echo "hello world"
      - name: spidy
        run: echo "my name is spider"
      
