name: boron

on: [push]

jobs:
  hello:
     runs-on: ubuntu-22.04

     steps:
       - name: checkout code
         uses: actions/checkout@v7

       - name: show files
         run: ls -la
       - name: say hello
         run: echo "hello from github"
       
 
