name: welcometomyworld

on: push

jobs:
  automate:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Run a test command
        run : ls -la
    
